<?php

global $_GESTOR;

$_GESTOR['modulo-id']							=	'testes';
$_GESTOR['modulo#'.$_GESTOR['modulo-id']]		=	Array(
	'versao' => '1.0.8',
	'bibliotecas' => Array('interface','html','pagina'),
	'tabela' => Array(
		'nome' => 'template',
		'id' => 'id',
		'id_numerico' => 'id_'.'template',
		'status' => 'status',
		'versao' => 'versao',
		'data_criacao' => 'data_criacao',
		'data_modificacao' => 'data_modificacao',
	),
);

function testes_testes(){
	global $_GESTOR;
	
	$pagina = '';
	
	// ===== Área de testes.
	
	// ===== Ler o SQL do banco de dados.
	
	$bancoSQL = "-- MySQL Script generated by MySQL Workbench
-- Tue Aug  9 11:16:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema b2make-escalas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema b2make-escalas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b2make-escalas` DEFAULT CHARACTER SET utf8mb4 ;
USE `b2make-escalas` ;

-- -----------------------------------------------------
-- Table `b2make-escalas`.`escalas_controle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2make-escalas`.`escalas_controle` (
  `id_escalas_controle` INT NOT NULL AUTO_INCREMENT,
  `id_hosts_escalas_controle` INT NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_escalas_controle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2make-escalas`.`escalas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2make-escalas`.`escalas` (
  `id_escalas` INT NOT NULL AUTO_INCREMENT,
  `id_hosts_escalas` INT NULL DEFAULT NULL,
  `id_hosts_ususarios` INT NULL DEFAULT NULL,
  `mes` INT NULL DEFAULT NULL,
  `ano` INT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `pubID` VARCHAR(255) NULL DEFAULT NULL,
  `versao` INT NULL DEFAULT NULL,
  `data_criacao` DATETIME NULL DEFAULT NULL,
  `data_modificacao` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_escalas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2make-escalas`.`escalas_datas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2make-escalas`.`escalas_datas` (
  `id_escalas_datas` INT NOT NULL AUTO_INCREMENT,
  `id_hosts_escalas_datas` INT NULL DEFAULT NULL,
  `id_hosts_escalas` INT NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_escalas_datas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2make-escalas`.`escalas_pesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2make-escalas`.`escalas_pesos` (
  `id_escalas_pesos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts_escalas_pesos` INT NULL DEFAULT NULL,
  `id_hosts_usuarios` INT NULL DEFAULT NULL,
  `peso` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_escalas_pesos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
";
	
	// ===== Varrer todas as linhas do SQL cru.
	
	$tabelaAtual = '';
	$tabelaAberta = false;
	$tabelaFechada = false;
	$bancoDeDados['tabelas'] = Array();
	$tabelaAux = Array();
	
	foreach(preg_split("/((\r?\n)|(\r\n?))/", $bancoSQL) as $lineSQL){
		$lineSQL = trim($lineSQL);
		
		if(preg_match('/'.preg_quote('CREATE TABLE IF NOT EXISTS').'/', $lineSQL) > 0){
			$lineSQL = preg_replace('/`.*?`\./', '', $lineSQL);
			
			preg_match('/`.*?`/', $lineSQL, $matches);
			
			if($matches[0]){
				$tabelaAtual = ltrim(rtrim($matches[0],"`"),"`");
				$tabelaAberta = true;
				$tabelaAux[$tabelaAtual] = '';
			}
		}
		
		if($tabelaAberta){
			$tabelaAux[$tabelaAtual] .= $lineSQL."\r\n";
		}
		
		if(preg_match('/'.preg_quote('ENGINE').'/', $lineSQL) > 0){
			if($tabelaAberta){
				$tabelaAberta = false;
				$bancoDeDados['tabelas'][$tabelaAtual] = $tabelaAux[$tabelaAtual];
			}
		}
	}
	
	$pagina = print_r($bancoDeDados,true);
	
	// ===== Inclusão Módulo JS
	
	gestor_pagina_javascript_incluir();
	
	// ===== Alteração da página.
	
	$_GESTOR['pagina'] .= $pagina;
	
}

function testes_interfaces_padroes(){
	global $_GESTOR;
	
	$modulo = $_GESTOR['modulo#'.$_GESTOR['modulo-id']];
	
	switch($_GESTOR['opcao']){
		case 'listar':
			
		break;
	}
}

// ==== Ajax

function testes_ajax_opcao(){
	global $_GESTOR;
	
	$_GESTOR['ajax-json'] = Array(
		'status' => 'Ok',
	);
}

// ==== Start

function testes_start(){
	global $_GESTOR;
	
	gestor_incluir_bibliotecas();
	
	if($_GESTOR['ajax']){
		interface_ajax_iniciar();
		
		switch($_GESTOR['ajax-opcao']){
			//case 'opcao': testes_ajax_opcao(); break;
		}
		
		interface_ajax_finalizar();
	} else {
		testes_interfaces_padroes();
		
		interface_iniciar();
		
		switch($_GESTOR['opcao']){
			case 'testes': testes_testes(); break;
		}
		
		interface_finalizar();
	}
}

testes_start();

?>