<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;

final class BancoV2PostgreSqlTest extends TestCase
{
    private static ?BancoV2 $database = null;
    private const TABLE = 'c2f_banco_v2_pg_test';

    public static function setUpBeforeClass(): void
    {
        if (PHP_VERSION_ID < 80500) {
            self::markTestSkipped('banco-v2.php currently requires PHP 8.5 or newer.');
        }
        if (getenv('CONN2FLOW_RUN_PGSQL_TESTS') !== '1') {
            self::markTestSkipped('Set CONN2FLOW_RUN_PGSQL_TESTS=1 to run PostgreSQL integration tests.');
        }
        if (!extension_loaded('pdo_pgsql')) {
            self::markTestSkipped('The pdo_pgsql extension is required.');
        }

        require_once CONN2FLOW_GESTOR_ROOT . '/bibliotecas/banco-v2.php';

        $config = new ConfigBanco(
            driver: DriverBanco::PostgreSQL,
            host: getenv('CONN2FLOW_DB_HOST') ?: 'postgres',
            porta: (int)(getenv('CONN2FLOW_DB_PORT') ?: 5432),
            nome: getenv('CONN2FLOW_DB_DATABASE') ?: 'conn2flow',
            usuario: getenv('CONN2FLOW_DB_USERNAME') ?: 'conn2flow_user',
            senha: getenv('CONN2FLOW_DB_PASSWORD') ?: 'conn2flow_pass',
            charset: 'UTF8',
            schema: getenv('CONN2FLOW_DB_SCHEMA') ?: 'public',
            sslmode: getenv('CONN2FLOW_DB_SSLMODE') ?: 'disable',
            applicationName: 'conn2flow-tests',
        );

        self::$database = (new BancoV2($config))->setDebug(true);
        $table = self::$database->quoteIdentifier(self::TABLE);
        self::$database->executar("DROP TABLE IF EXISTS {$table} CASCADE");
        self::$database->executar(
            "CREATE TABLE {$table} (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                external_id VARCHAR(64) NOT NULL UNIQUE,
                name VARCHAR(255) NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )",
        );
    }

    protected function setUp(): void
    {
        if (self::$database === null) {
            self::markTestSkipped('PostgreSQL integration database is not configured.');
        }

        $table = self::$database->quoteIdentifier(self::TABLE);
        self::$database->executar("TRUNCATE TABLE {$table} RESTART IDENTITY");
    }

    public static function tearDownAfterClass(): void
    {
        if (self::$database !== null) {
            $table = self::$database->quoteIdentifier(self::TABLE);
            self::$database->executar("DROP TABLE IF EXISTS {$table} CASCADE");
        }
    }

    public function testConnectionCrudMetadataAndIdentity(): void
    {
        $database = self::$database;
        self::assertNotNull($database);
        self::assertTrue($database->ping());
        self::assertSame(DriverBanco::PostgreSQL, $database->driver());

        $database->tabela(self::TABLE)->insert([
            'external_id' => 'first',
            'name' => 'First record',
        ]);

        self::assertSame(1, $database->ultimoId());
        self::assertContains(self::TABLE, $database->tabelasLista());
        self::assertTrue($database->campoExiste('external_id', self::TABLE));

        $row = $database->tabela(self::TABLE)
            ->where('external_id = ?', ['first'])
            ->selectUnico();

        self::assertSame('First record', $row['name'] ?? null);
        self::assertContains('external_id', $database->camposNomes(self::TABLE) ?? []);
    }

    public function testPostgreSqlUpsertIsAtomic(): void
    {
        $database = self::$database;
        self::assertNotNull($database);

        $database->tabela(self::TABLE)->upsert([
            'external_id' => 'same-id',
            'name' => 'Before',
        ], 'external_id');

        $database->tabela(self::TABLE)->upsert([
            'external_id' => 'same-id',
            'name' => 'After',
        ], 'external_id');

        $row = $database->tabela(self::TABLE)
            ->where('external_id = ?', ['same-id'])
            ->selectUnico();

        self::assertSame('After', $row['name'] ?? null);
        self::assertSame(1, $database->tabela(self::TABLE)->count());
    }

    public function testTransactionRollsBackOnFailure(): void
    {
        $database = self::$database;
        self::assertNotNull($database);

        try {
            $database->transacao(static function (BancoV2 $db): void {
                $db->tabela(self::TABLE)->insert([
                    'external_id' => 'rollback',
                    'name' => 'Must not persist',
                ]);
                throw new RuntimeException('force rollback');
            });
            self::fail('The transaction callback should throw.');
        } catch (RuntimeException $exception) {
            self::assertSame('force rollback', $exception->getMessage());
        }

        self::assertSame(0, $database->tabela(self::TABLE)->count());
    }
}
