<?php

declare(strict_types=1);

namespace Conn2Flow\Cli\Commands;

use Conn2Flow\Cli\Contracts\InputInterface;
use Conn2Flow\Cli\Contracts\OutputInterface;
use Conn2Flow\Cli\Support\Docs\DocsTree;
use Conn2Flow\Cli\Support\Docs\LibraryReference;
use Conn2Flow\Cli\Support\Docs\PhpFunctionExtractor;

/**
 * `c2f docs:extract` — regenera o bloco de referência das bibliotecas a partir do código (req-177).
 */
final class DocsExtractCommand extends BaseProcessCommand
{
    private const SKELETON = [
        'pt-br' => [
            'title' => 'Biblioteca %s.php',
            'overview' => 'Visão geral',
            'todo' => "> [!IMPORTANT]\n> Esqueleto gerado por `c2f docs:extract --create`. Leia `%s`, os chamadores e os testes antes de escrever; preencha `description` e `verified_at` e explique cada função abaixo.",
            'functions' => 'Funções',
        ],
        'en' => [
            'title' => '%s.php library',
            'overview' => 'Overview',
            'todo' => "> [!IMPORTANT]\n> Skeleton generated by `c2f docs:extract --create`. Read `%s`, its callers and tests before writing; fill in `description` and `verified_at` and explain each function below.",
            'functions' => 'Functions',
        ],
    ];

    public function getName(): string
    {
        return 'docs:extract';
    }

    public function getDescription(): string
    {
        return 'Regenerate the function reference block of library docs from gestor/bibliotecas/*.php.';
    }

    public function getAliases(): array
    {
        return [];
    }

    public function getHelp(): string
    {
        return "Usage: c2f docs:extract <library>|--all [--check] [--create] [--source=<dir>]\n\n"
            . "Rewrites the <!-- c2f:extract:start --> block of reference/libraries/<library>.md in every language.\n\n"
            . "  --all      every library that already has a doc (with --create: every library)\n"
            . "  --check    do not write; exit 1 if any block is missing or stale\n"
            . "  --create   scaffold missing docs (pt-br and en) with frontmatter and the block";
    }

    public function execute(InputInterface $input, OutputInterface $output): int
    {
        $source = $input->getOption('source');
        $tree = new DocsTree($this->rootPath, is_string($source) ? $source : null);
        $check = $input->hasOption('check');
        $create = $input->hasOption('create');

        $libs = $this->targets($input, $tree, $create);
        if ($libs === null) {
            $output->error('Inform a library name (e.g. modelo) or --all.');

            return 1;
        }

        $stale = 0;
        foreach ($libs as $lib) {
            $sourceRel = 'gestor/bibliotecas/' . $lib . '.php';
            $sourceAbs = $this->rootPath . '/' . $sourceRel;
            if (!is_file($sourceAbs)) {
                $output->error("Library not found: {$sourceRel}");

                return 1;
            }
            $functions = PhpFunctionExtractor::extract((string)file_get_contents($sourceAbs));
            $rel = 'reference/libraries/' . $lib . '.md';

            foreach (DocsTree::LANGS as $lang) {
                $block = LibraryReference::render($functions, $sourceRel, $tree->repoRelative($lang, $rel), $lang);
                $path = $tree->docsDir($lang) . '/' . $rel;

                if (!is_file($path)) {
                    if (!$create) {
                        $output->warning("{$lang}:{$rel} does not exist (use --create to scaffold).");
                        $stale++;
                        continue;
                    }
                    if ($check) {
                        $stale++;
                        continue;
                    }
                    if (!is_dir(dirname($path))) {
                        mkdir(dirname($path), 0777, true);
                    }
                    file_put_contents($path, $this->skeleton($lib, $lang, $sourceRel, $block));
                    $output->success("Created {$lang}:{$rel} (" . count($functions) . ' functions)');
                    continue;
                }

                $content = (string)file_get_contents($path);
                if (LibraryReference::current($content) === $block) {
                    continue;
                }
                $stale++;
                if ($check) {
                    $output->warning("{$lang}:{$rel} block is missing or stale.");
                    continue;
                }
                file_put_contents($path, LibraryReference::replace($content, $block));
                $output->success("Updated {$lang}:{$rel} (" . count($functions) . ' functions)');
            }
        }

        if ($check) {
            if ($stale > 0) {
                return 1;
            }
            $output->success('All extract blocks are up to date.');
        }

        return 0;
    }

    /** @return list<string>|null */
    private function targets(InputInterface $input, DocsTree $tree, bool $create): ?array
    {
        $name = $input->getArgument(0);
        if (is_string($name) && $name !== '') {
            return [basename($name, '.php')];
        }
        if (!$input->hasOption('all')) {
            return null;
        }
        $libs = [];
        foreach (glob($this->rootPath . '/gestor/bibliotecas/*.php') ?: [] as $file) {
            $lib = basename($file, '.php');
            $rel = 'reference/libraries/' . $lib . '.md';
            if ($create || $tree->exists('pt-br', $rel) || $tree->exists('en', $rel)) {
                $libs[] = $lib;
            }
        }
        sort($libs, SORT_STRING);

        return $libs;
    }

    private function skeleton(string $lib, string $lang, string $sourceRel, string $block): string
    {
        $t = self::SKELETON[$lang] ?? self::SKELETON['en'];

        return "---\n"
            . 'title: "' . sprintf($t['title'], $lib) . "\"\n"
            . "description: \"\"\n"
            . "section: reference\n"
            . "order: 100\n"
            . "sources:\n"
            . "  - {$sourceRel}\n"
            . "verified_at: \"\"\n"
            . "---\n\n"
            . '# ' . sprintf($t['title'], $lib) . "\n\n"
            . sprintf($t['todo'], $sourceRel) . "\n\n"
            . '## ' . $t['overview'] . "\n\n"
            . '## ' . $t['functions'] . "\n\n"
            . $block . "\n";
    }
}
