<?php

// Script para traduzir admin-paginas_en.json
$file = __DIR__ . '/dictionaries/admin-paginas_en.json';

if (!file_exists($file)) {
    die("Arquivo não encontrado: $file\n");
}

$content = file_get_contents($file);
$data = json_decode($content, true);

if ($data === null) {
    die("Erro ao decodificar JSON\n");
}

$translations = [
    "Nome da Página" => "Page Name",
    "Clique para abrir o Editor HTML" => "Click to open HTML Editor",
    "Editor HTML" => "HTML Editor",
    "Clique para abrir o HTML > Corpo. Parte visível da página dentro da tag <body>" => "Click to open HTML > Body. Visible part of the page within the <body> tag",
    "HTML > Corpo" => "HTML > Body",
    "Clique para abrir o CSS" => "Click to open CSS",
    "Identificador" => "Identifier",
    "Caminho" => "Path",
    "Escolha um layout" => "Choose a layout",
    "Selecione um tipo" => "Select a type",
    "Selecione um módulo" => "Select a module",
    "Opção" => "Option",
    "Raiz" => "Root",
    "Sem Permissão" => "No Permission",
    "Configurações da Página" => "Page Settings",
    "Editor HTML Habilitar" => "Enable HTML Editor",
    "pelo menos uma '/' no final" => "at least one '/' at the end",
    "URL Atual da Página" => "Current Page URL",
    "Pré-Visualizar" => "Preview",
    "Clique para pré-visualizar a página" => "Click to preview the page",
    "Pré-Visualização da Página" => "Page Preview",
    "Computador" => "Computer",
    "Clique no botão para voltar." => "Click the button to go back.",
    "Voltar" => "Back",
    "Ambos" => "Both",
    "Clique para abrir o CSS automático gerado pelo sistema." => "Click to open the automatic CSS generated by the system.",
    "CSS Automático" => "Automatic CSS",
    "Clique para abrir o HTML extra para o Cabeçalho da página. Parte dentro da tag <head>" => "Click to open extra HTML for the page Header. Part within the <head> tag",
    "HTML > Cabeçalho" => "HTML > Header"
];

// Traduzir variables
foreach ($data['variables'] as $key => $value) {
    if (isset($translations[$value])) {
        $data['variables'][$key] = $translations[$value];
        echo "Traduzido variável: $key\n";
    }
}

// Traduzir components
$componentTranslations = [
    "Modal Página" => "Page Modal",
    "Lista Página ou Sistema" => "Page or System List"
];

if (isset($data['components'])) {
    foreach ($data['components'] as $key => $component) {
        if (isset($component['nome']) && isset($componentTranslations[$component['nome']])) {
            $data['components'][$key]['name'] = $componentTranslations[$component['nome']];
            unset($data['components'][$key]['nome']);
            echo "Traduzido componente: {$component['nome']}\n";
        }
    }
}

$newContent = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
file_put_contents($file, $newContent);

echo "✅ Tradução concluída!\n";

?>