-- MySQL Script generated by MySQL Workbench
-- Mon Jul 21 17:50:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema betaentr_gestor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema betaentr_gestor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `betaentr_gestor` DEFAULT CHARACTER SET utf8mb4 ;
USE `betaentr_gestor` ;

-- -----------------------------------------------------
-- Table `betaentr_gestor`.`paginas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`paginas` (
  `id_paginas` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `id_layouts` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `caminho` TEXT NULL,
  `tipo` VARCHAR(255) NULL,
  `modulo` VARCHAR(255) NULL,
  `opcao` VARCHAR(255) NULL,
  `raiz` TINYINT NULL,
  `sem_permissao` TINYINT NULL,
  `html` MEDIUMTEXT NULL,
  `css` MEDIUMTEXT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_paginas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`layouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`layouts` (
  `id_layouts` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `html` MEDIUMTEXT NULL,
  `css` MEDIUMTEXT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_layouts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`variaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`variaveis` (
  `id_variaveis` INT NOT NULL AUTO_INCREMENT,
  `linguagem_codigo` VARCHAR(10) NULL,
  `modulo` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `valor` TEXT NULL,
  `tipo` VARCHAR(100) NULL,
  `grupo` VARCHAR(255) NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_variaveis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`historico` (
  `id_historico` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `id_hosts_usuarios` INT NULL,
  `id_hosts` INT NULL,
  `modulo` VARCHAR(255) NULL,
  `id` INT NULL,
  `versao` INT NULL,
  `campo` VARCHAR(255) NULL,
  `opcao` VARCHAR(255) NULL,
  `filtro` VARCHAR(255) NULL,
  `alteracao` VARCHAR(255) NULL,
  `alteracao_txt` TEXT NULL,
  `valor_antes` TEXT NULL,
  `valor_depois` TEXT NULL,
  `tabela` TEXT NULL,
  `data` DATETIME NULL,
  `controlador` VARCHAR(255) NULL,
  PRIMARY KEY (`id_historico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios_perfis` INT NULL,
  `nome_conta` VARCHAR(255) NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `usuario` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `primeiro_nome` VARCHAR(100) NULL,
  `ultimo_nome` VARCHAR(100) NULL,
  `nome_do_meio` VARCHAR(100) NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `email_confirmado` TINYINT NULL,
  `gestor` TINYINT NULL,
  `gestor_perfil` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`backup_campos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`backup_campos` (
  `id_backup_campos` INT NOT NULL AUTO_INCREMENT,
  `modulo` VARCHAR(255) NULL,
  `id` INT NULL,
  `versao` INT NULL,
  `campo` VARCHAR(255) NULL,
  `valor` TEXT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`id_backup_campos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`modulos_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`modulos_grupos` (
  `id_modulos_grupos` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `host` TINYINT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `ordemMenu` INT NULL,
  PRIMARY KEY (`id_modulos_grupos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`modulos` (
  `id_modulos` INT NOT NULL AUTO_INCREMENT,
  `id_modulos_grupos` INT NULL,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `titulo` VARCHAR(255) NULL,
  `icone` VARCHAR(100) NULL,
  `icone2` VARCHAR(100) NULL,
  `nao_menu_principal` TINYINT NULL,
  `plugin` VARCHAR(255) NULL,
  `host` TINYINT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_modulos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`usuarios_perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`usuarios_perfis` (
  `id_usuarios_perfis` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `padrao` TINYINT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_usuarios_perfis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`usuarios_perfis_modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`usuarios_perfis_modulos` (
  `id_usuarios_perfis_modulos` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(255) NULL,
  `modulo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuarios_perfis_modulos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`usuarios_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`usuarios_tokens` (
  `id_usuarios_tokens` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `pubID` VARCHAR(100) NULL,
  `pubIDValidation` VARCHAR(150) NULL,
  `fingerprint` VARCHAR(100) NULL,
  `expiration` INT NULL,
  `ip` VARCHAR(100) NULL,
  `user_agent` TEXT NULL,
  `origem` VARCHAR(255) NULL,
  `data_criacao` DATETIME NULL,
  `senha_incorreta_tentativas` INT NULL,
  PRIMARY KEY (`id_usuarios_tokens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`paginas_301`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`paginas_301` (
  `id_paginas_301` INT NOT NULL AUTO_INCREMENT,
  `id_paginas` INT NULL,
  `caminho` TEXT NULL,
  `data_criacao` DATETIME NULL,
  PRIMARY KEY (`id_paginas_301`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`sessoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`sessoes` (
  `id_sessoes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(100) NULL,
  `acesso` INT UNSIGNED NULL,
  PRIMARY KEY (`id_sessoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`sessoes_variaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`sessoes_variaveis` (
  `id_sessoes_variaveis` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_sessoes` INT NULL,
  `variavel` TEXT NULL,
  `valor` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_sessoes_variaveis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`tokens` (
  `id_tokens` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `id` VARCHAR(100) NULL,
  `pubID` VARCHAR(150) NULL,
  `expiration` INT NULL,
  `data_criacao` DATETIME NULL,
  PRIMARY KEY (`id_tokens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`categorias` (
  `id_categorias` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `id_modulos` INT NULL,
  `id_categorias_pai` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `plugin` VARCHAR(255) NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_categorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`arquivos` (
  `id_arquivos` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `tipo` VARCHAR(100) NULL,
  `caminho` TEXT NULL,
  `caminho_mini` TEXT NULL,
  `permissao` TINYINT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_arquivos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`arquivos_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`arquivos_categorias` (
  `id_arquivos_categorias` INT NOT NULL AUTO_INCREMENT,
  `id_arquivos` INT NULL,
  `id_categorias` INT NULL,
  PRIMARY KEY (`id_arquivos_categorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`templates` (
  `id_templates` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `id_categorias_pai` INT NULL,
  `id_categorias` INT NULL,
  `id_arquivos_Imagem` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `html` MEDIUMTEXT NULL,
  `css` MEDIUMTEXT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `padrao` TINYINT NULL,
  PRIMARY KEY (`id_templates`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`usuarios_planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`usuarios_planos` (
  `id_usuarios_planos` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `cpanel_plano` VARCHAR(255) NULL,
  `ordem` VARCHAR(255) NULL,
  `publico` TINYINT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_usuarios_planos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`usuarios_planos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`usuarios_planos_usuarios` (
  `id_usuarios_planos_usuarios` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `id_usuarios_planos` INT NULL,
  `status` CHAR(1) NULL,
  `data_criacao` DATETIME NULL,
  `data_aprovacao` DATETIME NULL,
  `data_finalizacao` DATETIME NULL,
  PRIMARY KEY (`id_usuarios_planos_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts` (
  `id_hosts` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `pub_id` VARCHAR(100) NULL,
  `pre_configurado` TINYINT NULL,
  `instalado` TINYINT NULL,
  `configurado` TINYINT NULL,
  `atualizar` TINYINT NULL,
  `user_cpanel` VARCHAR(100) NULL,
  `user_ftp` VARCHAR(100) NULL,
  `user_db` VARCHAR(100) NULL,
  `server` VARCHAR(100) NULL,
  `dominio` VARCHAR(255) NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `chave_publica` TEXT NULL,
  `gestor_cliente_versao` VARCHAR(100) NULL,
  `gestor_cliente_versao_num` INT NULL,
  `dominio_proprio` TINYINT NULL,
  `dominio_proprio_url` VARCHAR(255) NULL,
  `google_recaptcha_ativo` TINYINT NULL,
  `google_recaptcha_site` VARCHAR(255) NULL,
  `google_recaptcha_secret` VARCHAR(255) NULL,
  `google_recaptcha_v2_ativo` TINYINT NULL,
  `google_recaptcha_v2_site` VARCHAR(255) NULL,
  `google_recaptcha_v2_secret` VARCHAR(255) NULL,
  `google_recaptcha_tipo` VARCHAR(100) NULL,
  PRIMARY KEY (`id_hosts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`usuarios_gestores_hosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`usuarios_gestores_hosts` (
  `id_usuarios_gestores_hosts` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `privilegios_admin` TINYINT NULL,
  PRIMARY KEY (`id_usuarios_gestores_hosts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_usuarios` (
  `id_hosts_usuarios` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_usuarios_perfis` INT NULL,
  `nome_conta` VARCHAR(255) NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `usuario` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `telefone` VARCHAR(100) NULL,
  `primeiro_nome` VARCHAR(100) NULL,
  `ultimo_nome` VARCHAR(100) NULL,
  `nome_do_meio` VARCHAR(100) NULL,
  `cnpj_ativo` TINYINT NULL,
  `cpf` VARCHAR(30) NULL,
  `cnpj` VARCHAR(30) NULL,
  `ppp_remembered_card_hash` VARCHAR(255) NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`modulos_operacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`modulos_operacoes` (
  `id_modulos_operacoes` INT NOT NULL AUTO_INCREMENT,
  `id_modulos` INT NULL,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `operacao` VARCHAR(255) NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_modulos_operacoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`usuarios_perfis_modulos_operacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`usuarios_perfis_modulos_operacoes` (
  `id_usuarios_perfis_modulos_operacoes` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(255) NULL,
  `operacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuarios_perfis_modulos_operacoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_layouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_layouts` (
  `id_hosts_layouts` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `html` MEDIUMTEXT NULL,
  `css` MEDIUMTEXT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `template_padrao` TINYINT NULL,
  `template_categoria` VARCHAR(255) NULL,
  `template_id` VARCHAR(255) NULL,
  `template_modificado` TINYINT NULL,
  `template_versao` INT NULL,
  PRIMARY KEY (`id_hosts_layouts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_paginas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_paginas` (
  `id_hosts_paginas` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `id_hosts_layouts` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `caminho` TEXT NULL,
  `tipo` VARCHAR(255) NULL,
  `modulo` VARCHAR(255) NULL,
  `modulo_id_registro` INT NULL,
  `sem_permissao` TINYINT NULL,
  `html` MEDIUMTEXT NULL,
  `css` MEDIUMTEXT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `template_padrao` TINYINT NULL,
  `template_categoria` VARCHAR(255) NULL,
  `template_id` VARCHAR(255) NULL,
  `template_modificado` TINYINT NULL,
  `template_versao` INT NULL,
  PRIMARY KEY (`id_hosts_paginas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_variaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_variaveis` (
  `id_hosts_variaveis` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `linguagem_codigo` VARCHAR(10) NULL,
  `modulo` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `valor` TEXT NULL,
  `tipo` VARCHAR(100) NULL,
  `grupo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_hosts_variaveis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_paginas_301`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_paginas_301` (
  `id_hosts_paginas_301` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_paginas` INT NULL,
  `caminho` TEXT NULL,
  `data_criacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_paginas_301`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`plataforma_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`plataforma_tokens` (
  `id_plataforma_tokens` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `pubID` VARCHAR(100) NULL,
  `pubIDValidation` VARCHAR(150) NULL,
  `expiration` INT NULL,
  `data_criacao` DATETIME NULL,
  `remoto` TINYINT NULL,
  PRIMARY KEY (`id_plataforma_tokens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_arquivos` (
  `id_hosts_arquivos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `tipo` VARCHAR(100) NULL,
  `caminho` TEXT NULL,
  `caminho_mini` TEXT NULL,
  `permissao` TINYINT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_arquivos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_categorias` (
  `id_hosts_categorias` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `id_modulos` INT NULL,
  `id_hosts_categorias_pai` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_categorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_arquivos_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_arquivos_categorias` (
  `id_hosts_arquivos_categorias` INT NOT NULL AUTO_INCREMENT,
  `id_hosts_arquivos` INT NULL,
  `id_hosts_categorias` INT NULL,
  PRIMARY KEY (`id_hosts_arquivos_categorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_servicos` (
  `id_hosts_servicos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `id_hosts_paginas` INT NULL,
  `id_hosts_arquivos_Imagem` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `template_id` VARCHAR(255) NULL,
  `template_tipo` VARCHAR(255) NULL,
  `preco` FLOAT NULL,
  `quantidade` INT NULL,
  `quantidade_carrinhos` INT NULL,
  `quantidade_pedidos_pendentes` INT NULL,
  `quantidade_pedidos` INT NULL,
  `descricao` MEDIUMTEXT NULL,
  `caminho` TEXT NULL,
  `lotesVariacoes` TINYINT NULL,
  `gratuito` TINYINT NULL,
  PRIMARY KEY (`id_hosts_servicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_templates` (
  `id_hosts_templates` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `id_categorias_pai` INT NULL,
  `id_categorias` INT NULL,
  `id_hosts_arquivos_Imagem` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `html` MEDIUMTEXT NULL,
  `css` MEDIUMTEXT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `padrao` TINYINT NULL,
  `ativo` TINYINT NULL,
  PRIMARY KEY (`id_hosts_templates`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_carrinho` (
  `id_hosts_carrinho` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `sessao_id` VARCHAR(255) NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_carrinho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_carrinho_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_carrinho_servicos` (
  `id_hosts_carrinho_servicos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_carrinho` INT NULL,
  `id_hosts_servicos` INT NULL,
  `id_hosts_arquivos_Imagem` INT NULL,
  `nome` VARCHAR(255) NULL,
  `preco` FLOAT NULL,
  `quantidade` INT NULL,
  `gratuito` TINYINT NULL,
  PRIMARY KEY (`id_hosts_carrinho_servicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_pedidos` (
  `id_hosts_pedidos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_usuarios` INT NULL,
  `id` VARCHAR(255) NULL,
  `codigo` VARCHAR(255) NULL,
  `total` FLOAT NULL,
  `live` TINYINT NULL,
  `status` VARCHAR(255) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `voucher_chave` TEXT NULL,
  `jwt_emitidos` TINYINT NULL,
  `jwt_bd_expiracao` DATETIME NULL,
  `jwt_bd_expirado` TINYINT NULL,
  PRIMARY KEY (`id_hosts_pedidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_pedidos_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_pedidos_servicos` (
  `id_hosts_pedidos_servicos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_pedidos` INT NULL,
  `id_hosts_servicos` INT NULL,
  `id_hosts_arquivos_Imagem` INT NULL,
  `nome` VARCHAR(255) NULL,
  `preco` FLOAT NULL,
  `quantidade` INT NULL,
  `gratuito` TINYINT NULL,
  PRIMARY KEY (`id_hosts_pedidos_servicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_usuarios_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_usuarios_tokens` (
  `id_hosts_usuarios_tokens` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_usuarios` INT NULL,
  `pubID` VARCHAR(100) NULL,
  `expiration` INT NULL,
  `ip` VARCHAR(100) NULL,
  `user_agent` TEXT NULL,
  `data_criacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_usuarios_tokens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_tokens` (
  `id_hosts_tokens` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_usuarios` INT NULL,
  `id` VARCHAR(100) NULL,
  `pubID` VARCHAR(150) NULL,
  `expiration` INT NULL,
  `data_criacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_tokens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_vouchers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_vouchers` (
  `id_hosts_vouchers` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_pedidos` INT NULL,
  `id_hosts_servicos` INT NULL,
  `id_hosts_servicos_variacoes` INT NULL,
  `codigo` VARCHAR(255) NULL,
  `nome` VARCHAR(255) NULL,
  `documento` VARCHAR(255) NULL,
  `telefone` VARCHAR(255) NULL,
  `status` VARCHAR(255) NULL,
  `jwt_bd` TEXT NULL,
  `loteVariacao` TINYINT NULL,
  `data_uso` DATETIME NULL,
  PRIMARY KEY (`id_hosts_vouchers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_paypal` (
  `id_hosts_paypal` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `app_installed` TINYINT NULL,
  `app_active` TINYINT NULL,
  `app_live` TINYINT NULL,
  `app_code` VARCHAR(255) NULL,
  `app_secret` VARCHAR(255) NULL,
  `app_token` VARCHAR(255) NULL,
  `app_token_time` INT NULL,
  `app_expires_in` INT NULL,
  `app_webhook_id` VARCHAR(255) NULL,
  `app_sandbox_code` VARCHAR(255) NULL,
  `app_sandbox_secret` VARCHAR(255) NULL,
  `app_sandbox_token` VARCHAR(255) NULL,
  `app_sandbox_token_time` INT NULL,
  `app_sandbox_expires_in` INT NULL,
  `app_sandbox_webhook_id` VARCHAR(255) NULL,
  `reference_installed` TINYINT NULL,
  `reference_id` VARCHAR(255) NULL,
  `reference_cancel_url` VARCHAR(255) NULL,
  `paypal_plus_inactive` TINYINT NULL,
  PRIMARY KEY (`id_hosts_paypal`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_paypal_pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_paypal_pagamentos` (
  `id_hosts_paypal_pagamentos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_pedidos` INT NULL,
  `pay_id` VARCHAR(100) NULL,
  `final_id` VARCHAR(100) NULL,
  `parcelas` INT NULL,
  `pagador_primeiro_nome` VARCHAR(100) NULL,
  `pagador_ultimo_nome` VARCHAR(100) NULL,
  `pagador_email` VARCHAR(100) NULL,
  `pagador_telefone` VARCHAR(100) NULL,
  `pagador_cpf` VARCHAR(30) NULL,
  `pagador_cnpj` VARCHAR(30) NULL,
  `pagador_selecionou_cnpj` TINYINT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `live` TINYINT NULL,
  `status` VARCHAR(100) NULL,
  PRIMARY KEY (`id_hosts_paypal_pagamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_paypal_gestor_taxas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_paypal_gestor_taxas` (
  `id_hosts_paypal_gestor_taxas` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_pedidos` INT NULL,
  `pay_id` VARCHAR(100) NULL,
  `data` DATETIME NULL,
  `valor` FLOAT NULL,
  `live` TINYINT NULL,
  PRIMARY KEY (`id_hosts_paypal_gestor_taxas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_postagens` (
  `id_hosts_postagens` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `id_hosts_paginas` INT NULL,
  `id_hosts_arquivos_Imagem` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `template_id` VARCHAR(255) NULL,
  `template_tipo` VARCHAR(255) NULL,
  `descricao` MEDIUMTEXT NULL,
  `caminho` TEXT NULL,
  PRIMARY KEY (`id_hosts_postagens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`componentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`componentes` (
  `id_componentes` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `modulo` VARCHAR(255) NULL,
  `html` MEDIUMTEXT NULL,
  `css` MEDIUMTEXT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_componentes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_componentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_componentes` (
  `id_hosts_componentes` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `modulo` VARCHAR(255) NULL,
  `html` MEDIUMTEXT NULL,
  `css` MEDIUMTEXT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `template_padrao` TINYINT NULL,
  `template_categoria` VARCHAR(255) NULL,
  `template_id` VARCHAR(255) NULL,
  `template_modificado` TINYINT NULL,
  `template_versao` INT NULL,
  PRIMARY KEY (`id_hosts_componentes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_servicos_lotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_servicos_lotes` (
  `id_hosts_servicos_lotes` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `id_hosts_servicos` INT NULL,
  `nome` VARCHAR(255) NULL,
  `visibilidade` VARCHAR(20) NULL,
  `dataInicio` DATETIME NULL,
  `dataFim` DATETIME NULL,
  PRIMARY KEY (`id_hosts_servicos_lotes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_servicos_variacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_servicos_variacoes` (
  `id_hosts_servicos_variacoes` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_usuarios` INT NULL,
  `id_hosts_servicos` INT NULL,
  `id_hosts_servicos_lotes` INT NULL,
  `nome` VARCHAR(255) NULL,
  `preco` FLOAT NULL,
  `quantidade` INT NULL,
  `quantidade_carrinhos` INT NULL,
  `quantidade_pedidos_pendentes` INT NULL,
  `quantidade_pedidos` INT NULL,
  `gratuito` TINYINT NULL,
  PRIMARY KEY (`id_hosts_servicos_variacoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_carrinho_servico_variacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_carrinho_servico_variacoes` (
  `id_hosts_carrinho_servico_variacoes` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_carrinho` INT NULL,
  `id_hosts_servicos` INT NULL,
  `id_hosts_servicos_lotes` INT NULL,
  `id_hosts_servicos_variacoes` INT NULL,
  `id_hosts_arquivos_Imagem` INT NULL,
  `nome_servico` VARCHAR(255) NULL,
  `nome_lote` VARCHAR(255) NULL,
  `nome_variacao` VARCHAR(255) NULL,
  `preco` FLOAT NULL,
  `quantidade` INT NULL,
  `gratuito` TINYINT NULL,
  PRIMARY KEY (`id_hosts_carrinho_servico_variacoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_pedidos_servico_variacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_pedidos_servico_variacoes` (
  `id_hosts_pedidos_servico_variacoes` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_pedidos` INT NULL,
  `id_hosts_servicos` INT NULL,
  `id_hosts_servicos_lotes` INT NULL,
  `id_hosts_servicos_variacoes` INT NULL,
  `id_hosts_arquivos_Imagem` INT NULL,
  `nome_servico` VARCHAR(255) NULL,
  `nome_lote` VARCHAR(255) NULL,
  `nome_variacao` VARCHAR(255) NULL,
  `preco` FLOAT NULL,
  `quantidade` INT NULL,
  `gratuito` TINYINT NULL,
  PRIMARY KEY (`id_hosts_pedidos_servico_variacoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`plugins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`plugins` (
  `id_plugins` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_plugins`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_plugins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_plugins` (
  `id_hosts_plugins` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `plugin` VARCHAR(255) NULL,
  `versao` VARCHAR(100) NULL,
  `versao_num` INT NULL,
  `habilitado` TINYINT NULL,
  `versao_config` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_plugins`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_configuracoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_configuracoes` (
  `id_hosts_configuracoes` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `modulo` VARCHAR(255) NULL,
  `versao` INT NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_configuracoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_menus_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_menus_itens` (
  `id_hosts_menus_itens` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `menu_id` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `label` VARCHAR(255) NULL,
  `tipo` VARCHAR(255) NULL,
  `url` VARCHAR(255) NULL,
  `inativo` TINYINT NULL,
  `versao` INT NULL,
  PRIMARY KEY (`id_hosts_menus_itens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_agendamentos_datas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_agendamentos_datas` (
  `id_hosts_agendamentos_datas` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `data` DATE NULL,
  `total` INT NULL,
  `status` VARCHAR(255) NULL,
  PRIMARY KEY (`id_hosts_agendamentos_datas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_agendamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_agendamentos` (
  `id_hosts_agendamentos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_usuarios` INT NULL,
  `data` DATE NULL,
  `acompanhantes` INT NULL,
  `senha` VARCHAR(100) NULL,
  `status` VARCHAR(100) NULL,
  `pubID` VARCHAR(255) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_agendamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_agendamentos_acompanhantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_agendamentos_acompanhantes` (
  `id_hosts_agendamentos_acompanhantes` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_agendamentos` INT NULL,
  `id_hosts_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id_hosts_agendamentos_acompanhantes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_agendamentos_pesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_agendamentos_pesos` (
  `id_hosts_agendamentos_pesos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_usuarios` INT NULL,
  `peso` INT NULL,
  PRIMARY KEY (`id_hosts_agendamentos_pesos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_conjunto_cupons_prioridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_conjunto_cupons_prioridade` (
  `id_hosts_conjunto_cupons_prioridade` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `quantidade` INT NULL,
  `valido_de` DATE NULL,
  `valido_ate` DATE NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_conjunto_cupons_prioridade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_cupons_prioridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_cupons_prioridade` (
  `id_hosts_cupons_prioridade` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_conjunto_cupons_prioridade` INT NULL,
  `id_hosts_agendamentos` INT NULL,
  `codigo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_hosts_cupons_prioridade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`usuarios_gestores_perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`usuarios_gestores_perfis` (
  `id_usuarios_gestores_perfis` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_usuarios_gestores_perfis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`usuarios_gestores_perfis_modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`usuarios_gestores_perfis_modulos` (
  `id_usuarios_gestores_perfis_modulos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `perfil` VARCHAR(255) NULL,
  `modulo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuarios_gestores_perfis_modulos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`usuarios_gestores_perfis_modulos_operacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`usuarios_gestores_perfis_modulos_operacoes` (
  `id_usuarios_gestores_perfis_modulos_operacoes` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `perfil` VARCHAR(255) NULL,
  `operacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuarios_gestores_perfis_modulos_operacoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_usuarios_perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_usuarios_perfis` (
  `id_hosts_usuarios_perfis` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `padrao` TINYINT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_usuarios_perfis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_usuarios_perfis_modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_usuarios_perfis_modulos` (
  `id_hosts_usuarios_perfis_modulos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `perfil` VARCHAR(255) NULL,
  `modulo` VARCHAR(255) NULL,
  PRIMARY KEY (`id_hosts_usuarios_perfis_modulos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_usuarios_perfis_modulos_operacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_usuarios_perfis_modulos_operacoes` (
  `id_hosts_usuarios_perfis_modulos_operacoes` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `perfil` VARCHAR(255) NULL,
  `operacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_hosts_usuarios_perfis_modulos_operacoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_escalas_controle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_escalas_controle` (
  `id_hosts_escalas_controle` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `data` DATE NULL,
  `total` INT NULL,
  `status` VARCHAR(255) NULL,
  PRIMARY KEY (`id_hosts_escalas_controle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_escalas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_escalas` (
  `id_hosts_escalas` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_usuarios` INT NULL,
  `mes` INT NULL,
  `ano` INT NULL,
  `status` VARCHAR(255) NULL,
  `pubID` VARCHAR(255) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  `data_confirmacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_escalas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_escalas_datas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_escalas_datas` (
  `id_hosts_escalas_datas` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_escalas` INT NULL,
  `data` DATE NULL,
  `status` VARCHAR(255) NULL,
  `selecionada` TINYINT NULL,
  `selecionada_inscricao` TINYINT NULL,
  `selecionada_confirmacao` TINYINT NULL,
  PRIMARY KEY (`id_hosts_escalas_datas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_escalas_pesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_escalas_pesos` (
  `id_hosts_escalas_pesos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `id_hosts_usuarios` INT NULL,
  `peso` INT NULL,
  PRIMARY KEY (`id_hosts_escalas_pesos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`hosts_escalas_cron`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`hosts_escalas_cron` (
  `id_hosts_escalas_cron` INT NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `mes` INT NULL,
  `ano` INT NULL,
  `status` VARCHAR(100) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_hosts_escalas_cron`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`acessos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`acessos` (
  `id_acessos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_hosts` INT NULL,
  `ip` VARCHAR(100) NULL,
  `quantidade` INT NULL,
  `bloqueios` INT NULL,
  `tipo` VARCHAR(100) NULL,
  `tempo_bloqueio` INT NULL,
  `tempo_modificacao` INT NULL,
  `status` VARCHAR(100) NULL,
  PRIMARY KEY (`id_acessos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`formularios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`formularios` (
  `id_formularios` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(255) NULL,
  `nome` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `telefone` VARCHAR(30) NULL,
  `mensagem` TEXT NULL,
  `status` CHAR(1) NULL,
  `versao` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_formularios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betaentr_gestor`.`plugins_hosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betaentr_gestor`.`plugins_hosts` (
  `id_plugins_hosts` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NULL,
  `nome` VARCHAR(255) NULL,
  `id` VARCHAR(255) NULL,
  `publico` TINYINT NULL,
  `diretorio` VARCHAR(255) NULL,
  `git` TINYINT NULL,
  `versao` INT NULL,
  `status` CHAR(1) NULL,
  `data_criacao` DATETIME NULL,
  `data_modificacao` DATETIME NULL,
  PRIMARY KEY (`id_plugins_hosts`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
