#!/bin/bash

# Script to verify and list all PT-BR resources of the system
# Author: AI Translation Agent
# Date: $(date '+%d/%m/%Y')

# Output colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to display header
show_header() {
    echo -e "${BLUE}"
    echo "=================================================="
    echo "   PT-BR RESOURCE VERIFIER - CONN2FLOW"
    echo "=================================================="
    echo -e "${NC}"
}

# Log function
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Variables
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
GESTOR_DIR="$PROJECT_ROOT/gestor"
LISTA_RECURSOS_FILE="$PROJECT_ROOT/ai-workspace/prompts/translates/pt-br/lista-recursos.md"
TRADUCAO_MAIN_FILE="$PROJECT_ROOT/ai-workspace/prompts/translates/traducao-pt-br-para-en.md"

# Counters
total_files=0
html_files=0
json_files=0
css_files=0

# Arrays to store files by type
declare -a html_array
declare -a json_array  
declare -a css_array

# Function to check if directory exists
check_directory() {
    if [ ! -d "$1" ]; then
        log_error "Directory not found: $1"
        return 1
    fi
    return 0
}

# Function to process files in a directory
process_directory() {
    local dir="$1"
    local context="$2"
    
    log_info "Processing: $context"
    
    # Search HTML files
    while IFS= read -r -d '' file; do
        if [ -f "$file" ]; then
            rel_path="${file#$PROJECT_ROOT/}"
            html_array+=("$rel_path")
            ((html_files++))
            ((total_files++))
        fi
    done < <(find "$dir" -name "*.html" -type f -print0 2>/dev/null)
    
    # Search JSON files
    while IFS= read -r -d '' file; do
        if [ -f "$file" ]; then
            rel_path="${file#$PROJECT_ROOT/}"
            json_array+=("$rel_path")
            ((json_files++))
            ((total_files++))
        fi
    done < <(find "$dir" -name "*.json" -type f -print0 2>/dev/null)
    
    # Search CSS files
    while IFS= read -r -d '' file; do
        if [ -f "$file" ]; then
            rel_path="${file#$PROJECT_ROOT/}"
            css_array+=("$rel_path")
            ((css_files++))
            ((total_files++))
        fi
    done < <(find "$dir" -name "*.css" -type f -print0 2>/dev/null)
}

# Function to create resource list file
create_resource_list() {
    log_info "Creating resource list file..."
    
    # Create directory if not exists
    mkdir -p "$(dirname "$LISTA_RECURSOS_FILE")"
    
    # Create file content
    cat > "$LISTA_RECURSOS_FILE" << EOF
# PT-BR Resource List for Translation

## 📊 General Statistics
- **Total Files**: $total_files
- **HTML Files**: $html_files
- **JSON Files**: $json_files  
- **CSS Files**: $css_files

*Last update: $(date '+%d/%m/%Y %H:%M:%S')*

## 📂 Resource Structure

### 🏗️ Global Resources
Location: \`gestor/resources/\`

### 🧩 Module Resources  
Location: \`gestor/modulos/{modulo-id}/resources/\`

## 📋 Complete File List

### 📄 HTML Files ($html_files files)
EOF

    # Add HTML files
    for file in "${html_array[@]}"; do
        echo "- [ ] \`$file\`" >> "$LISTA_RECURSOS_FILE"
    done
    
    # Add JSON section
    cat >> "$LISTA_RECURSOS_FILE" << EOF

### 📋 JSON Files ($json_files files)
EOF

    # Add JSON files
    for file in "${json_array[@]}"; do
        echo "- [ ] \`$file\`" >> "$LISTA_RECURSOS_FILE"
    done
    
    # Add CSS section
    cat >> "$LISTA_RECURSOS_FILE" << EOF

### 🎨 CSS Files ($css_files files)
EOF

    # Add CSS files
    for file in "${css_array[@]}"; do
        echo "- [ ] \`$file\`" >> "$LISTA_RECURSOS_FILE"
    done
    
    # Add footer
    cat >> "$LISTA_RECURSOS_FILE" << EOF

## 🔄 Translation Status

### ⏳ Pending
All files listed above are pending translation.

### ✅ Completed  
No files translated yet.

### ❌ With Problems
No problems identified yet.

## 📝 Observations
- List automatically generated by script \`verify-resources.sh\`
- File updated on: $(date '+%d/%m/%Y %H:%M:%S')
- To update this list, execute: \`bash ai-workspace/scripts/translates/verify-resources.sh\`

---
*Automatically generated on: $(date '+%d/%m/%Y %H:%M:%S')*
EOF

    log_info "List file created: $LISTA_RECURSOS_FILE"
}

# Function to update main document
update_main_document() {
    log_info "Updating main translation document..."
    
    # Create backup of original file
    if [ -f "$TRADUCAO_MAIN_FILE" ]; then
        cp "$TRADUCAO_MAIN_FILE" "$TRADUCAO_MAIN_FILE.bak"
        log_info "Backup created: $TRADUCAO_MAIN_FILE.bak"
    fi
    
    # Update statistics in main document
    # This will be done via sed to update specific lines
    if [ -f "$TRADUCAO_MAIN_FILE" ]; then
        # Update total files
        sed -i "s/- \*\*Total de Arquivos\*\*: [0-9]* (será atualizado)/- **Total Files**: $total_files/" "$TRADUCAO_MAIN_FILE"
        
        # Update HTML files
        sed -i "s/- \*\*HTML\*\*: [0-9]*\/[0-9]* ([0-9]*%)/- **HTML**: 0\/$html_files (0%)/" "$TRADUCAO_MAIN_FILE"
        
        # Update JSON files  
        sed -i "s/- \*\*JSON\*\*: [0-9]*\/[0-9]* ([0-9]*%)/- **JSON**: 0\/$json_files (0%)/" "$TRADUCAO_MAIN_FILE"
        
        # Update CSS files
        sed -i "s/- \*\*CSS\*\*: [0-9]*\/[0-9]* ([0-9]*%)/- **CSS**: 0\/$css_files (0%)/" "$TRADUCAO_MAIN_FILE"
        
        log_info "Main document updated with new statistics"
    fi
}

# Main function
main() {
    show_header
    
    log_info "Starting PT-BR resource verification..."
    log_info "Project directory: $PROJECT_ROOT"
    
    # Check if directories exist
    if ! check_directory "$GESTOR_DIR"; then
        log_error "Manager directory not found!"
        exit 1
    fi
    
    # Process global resources
    if [ -d "$GESTOR_DIR/resources" ]; then
        process_directory "$GESTOR_DIR/resources" "Global Resources (gestor/resources/)"
    else
        log_warning "Global resources directory not found: $GESTOR_DIR/resources"
    fi
    
    # Process module resources
    if [ -d "$GESTOR_DIR/modulos" ]; then
        for modulo_dir in "$GESTOR_DIR/modulos"/*; do
            if [ -d "$modulo_dir" ] && [ -d "$modulo_dir/resources" ]; then
                modulo_name=$(basename "$modulo_dir")
                process_directory "$modulo_dir/resources" "Module: $modulo_name"
            fi
        done
    else
        log_warning "Modules directory not found: $GESTOR_DIR/modulos"
    fi
    
    # Display results
    echo -e "\n${BLUE}📊 VERIFICATION RESULTS${NC}"
    echo "=================================="
    echo -e "${GREEN}Total files found: $total_files${NC}"
    echo -e "  📄 HTML: $html_files"
    echo -e "  📋 JSON: $json_files"  
    echo -e "  🎨 CSS: $css_files"
    
    # Create list file
    create_resource_list
    
    # Update main document
    update_main_document
    
    echo -e "\n${GREEN}✅ Verification completed successfully!${NC}"
    echo -e "${BLUE}📁 Resource list created at:${NC} $LISTA_RECURSOS_FILE"
    echo -e "${BLUE}📝 Main document updated:${NC} $TRADUCAO_MAIN_FILE"
}

# Execute main function
main "$@"
