<?php

// ===== Caminho inicial do Gestor do Cliente

$_INDEX											=	Array();

$_INDEX['sistemas-dir']							=	'../b2make-gestor-cliente/';

// ===== Configuração Inicial do Gestor do Cliente.

$_GESTOR										=	Array();

$_GESTOR['bibliotecas']							=	Array('banco','modelo');

require_once($_INDEX['sistemas-dir'] . 'config-cliente.php');

// ===== Configuração deste host

require_once($_INDEX['sistemas-dir'] . 'config.php');

$_GESTOR['modulo-id']							=	'update-sys';

// ===== Funções Principais da atualização

function atualizar_banco_de_dados_sql(){
	return "
-- MySQL Script generated by MySQL Workbench
-- Tue Aug  9 10:54:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema b2make-escalas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `escalas_controle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escalas_controle` (
  `id_escalas_controle` INT NOT NULL AUTO_INCREMENT,
  `id_hosts_escalas_controle` INT NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_escalas_controle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escalas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escalas` (
  `id_escalas` INT NOT NULL AUTO_INCREMENT,
  `id_hosts_escalas` INT NULL DEFAULT NULL,
  `id_hosts_ususarios` INT NULL DEFAULT NULL,
  `mes` INT NULL DEFAULT NULL,
  `ano` INT NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `pubID` VARCHAR(255) NULL DEFAULT NULL,
  `versao` INT NULL DEFAULT NULL,
  `data_criacao` DATETIME NULL DEFAULT NULL,
  `data_modificacao` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_escalas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escalas_datas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escalas_datas` (
  `id_escalas_datas` INT NOT NULL AUTO_INCREMENT,
  `id_hosts_escalas_datas` INT NULL DEFAULT NULL,
  `id_hosts_escalas` INT NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_escalas_datas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escalas_pesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escalas_pesos` (
  `id_escalas_pesos` INT NOT NULL AUTO_INCREMENT,
  `id_hosts_escalas_pesos` INT NULL DEFAULT NULL,
  `id_hosts_usuarios` INT NULL DEFAULT NULL,
  `peso` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_escalas_pesos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
";
}

function atualizar_banco_de_dados(){
	// ===== Ler o SQL do banco de dados.
	
	$bancoSQL = atualizar_banco_de_dados_sql();
	
	// ===== Varrer todas as linhas do SQL cru.
	
	$tabelaAtual = '';
	$tabelaAberta = false;
	$tabelaFechada = false;
	$bancoDeDados['tabelas'] = Array();
	$tabelaAux = Array();
	
	foreach(preg_split("/((\r?\n)|(\r\n?))/", $bancoSQL) as $lineSQL){
		$lineSQL = trim($lineSQL);
		
		if(preg_match('/'.preg_quote('CREATE TABLE IF NOT EXISTS').'/', $lineSQL) > 0){
			preg_match('/`.*?`/', $lineSQL, $matches);
			
			if($matches[0]){
				$tabelaAtual = ltrim(rtrim($matches[0],"`"),"`");
				$tabelaAberta = true;
				$tabelaAux[$tabelaAtual] = '';
			}
		}
		
		if($tabelaAberta){
			$tabelaAux[$tabelaAtual] .= $lineSQL."\r\n";
		}
		
		if(preg_match('/'.preg_quote('ENGINE').'/', $lineSQL) > 0){
			if($tabelaAberta){
				$tabelaAberta = false;
				$bancoDeDados['tabelas'][$tabelaAtual] = $tabelaAux[$tabelaAtual];
			}
		}
	}
	
	// ===== Controlador para conferir se todas as tabelas foram processados.
	
	$tabelasProcessadas = Array();
	
	// ===== Varrear todas as tabelas.
	
	if(isset($bancoDeDados))
	foreach($bancoDeDados['tabelas'] as $tabela => $sql){
		// ===== Incluir a tabela no controlador 'tabelasProcessadas'.
		
		$tabelasProcessadas[] = $tabela;
		
		// ===== Criar tabela caso não exista, senão atualizar campos.
		
		$num = banco_num_rows(banco_query("SHOW TABLES LIKE '".$tabela."'"));
		
		if($num == 0){
			banco_query($sql);
		} else {
			// ===== Controlador para conferir se todos os campos foram processados.
			
			$camposProcessados = Array();
			
			// ===== Pegar todos os campos da tabela.
			
			$campos = banco_fields_names($tabela);
			
			// ===== Varrer todas as linhas do SQL.
			
			$alterTableAfter = '';
			foreach(preg_split("/((\r?\n)|(\r\n?))/", $sql) as $lineSQL){
				$lineSQL = trim($lineSQL);
				$line_arr = explode(' ',$lineSQL);
				
				if($line_arr[0]){
					switch($line_arr[0]){
						case 'CREATE':
						case 'ENGINE':
						case 'PRIMARY':
							// Ignorar lineSQL
						break;
						default:
							// ===== Caso encontre o padrão `campoNome`. Verifica se todos os campos existem.
						
							preg_match('/`.*?`/', $lineSQL, $matches);
							
							if($matches[0]){
								$campo = ltrim(rtrim($matches[0],"`"),"`");
								
								$foundCampo = false;
								if(isset($campos))
								foreach($campos as $campoBD){
									if($campo == $campoBD){
										$foundCampo = true;
										break;
									}
								}
								
								// ===== Caso não encontre um campo, altera a tabela e inclui a linha.
								
								if(!$foundCampo){
									$campoDados = rtrim($lineSQL,",");
									banco_query('ALTER TABLE `'.$tabela.'` ADD '.$campoDados . $alterTableAfter);
								}
								
								// ===== Incluir o campo no controlador 'camposProcessados'.
								
								$camposProcessados[] = $campo;

								// ===== After para colocar na sequência correta que vem do SQL.
								
								$alterTableAfter = ' AFTER `'.$campo.'`';
								
							}
							
					}
				}
			}
			
			// ===== Remover os campos não processados. Ou seja, que já foram excluídos do SQL.
			
			if(isset($campos))
			foreach($campos as $campoBD){
				$foundCampo = false;
				
				if(count($camposProcessados) > 0)
				foreach($camposProcessados as $campoProc){
					if($campoBD == $campoProc){
						$foundCampo = true;
						break;
					}
				}
				
				if(!$foundCampo){
					banco_query('ALTER TABLE `'.$tabela.'` DROP COLUMN '.$campoBD);
				}
			}
		}
	}
	
	// ===== Remover as tabelas não processadas. Ou seja, que já foram excluídos do SQL.
	
	// IMPORTANTE!!!! Plugins deletam tabelas que não são do plugin. Encontrar outra forma de excluir.
	
	/* $tabelasBD = banco_tabelas_lista();
	
	if(count($tabelasBD) > 0)
	foreach($tabelasBD as $tabelaBD){
		$foundTabela = false;
		
		if(count($tabelasProcessadas) > 0)
		foreach($tabelasProcessadas as $tabelaProc){
			if($tabelaBD == $tabelaProc){
				$foundTabela = true;
				break;
			}
		}
		
		if(!$foundTabela){
			banco_query('DROP TABLE IF EXISTS `'.$tabelaBD.'`');
		}
	} */
}

// ===== Interface principal

function main(){
	global $_GESTOR;
	
	// ===== Atualizar o banco de dados para a última versão.
	
	atualizar_banco_de_dados();
	
	// ===== Retornar o JSON com os status de retorno.
	
	$_GESTOR['json'] = Array(
		'status' => 'OK',
	);
	
	header("Content-Type: application/json; charset: UTF-8");
	echo json_encode($_GESTOR['json']);
}

main();

?>